// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwixrxoijdejaeqzgbmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13aXhyeG9pamRlamFlcXpnYm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjY0MjgsImV4cCI6MjA3MDkwMjQyOH0.sa63KrTNRzDzM6gC6TDTWTUN2Zf1jZtFXOKdwCd0VYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});