// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdepwplqxxwcbpyfucuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkZXB3cGxxeHh3Y2JweWZ1Y3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NjgzODQsImV4cCI6MjA4NDE0NDM4NH0.tK7U3sxkJ4VhiAbPzHyI6vEbXdJN6Q594xL-f3tFdpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});